### ISSUE TITLE
Create an hourlyplot module

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#100]
I'm just posting this topic because I did 15 minutes of research into it and I want to have a record of what I found (we still have some time before I implement a "3D chart" in the Ladybug core).  For anyone reading this issue, pleas post any thoughts here as I would really like feedback before doing this implementation.

One thing that I know @mostaphaRoudsari and I agree upon is that "3D Chart" should not be used to refer to this type of Ladybug visualization:
![color_library_rhino](https://user-images.githubusercontent.com/5567574/50375243-6c4b8f00-05c8-11e9-84c2-9f57a481d872.png)

This is not only because "3D Chart" is an incredibly vague term that can be used to describe almost any Ladybug graphic but also because, quite ironically, this graphic is rarely viewed in its 3D form since the colors are often a better way to observe the data rather than a 3D representation.

I know that @mostaphaRoudsari recommended re-naming the component to "heatmap" but after [checking the definition of a heatmap according to wikipedia](https://en.wikipedia.org/wiki/Heat_map), I am now of the opinion that this term is almost as vague as "3D Chart" and can also refer to a variety of graphics.  Specifically, it seems that "heatmap" can refer to any matrix where cells are colored according to data and, by this logic, the adaptive comfort chart is also a heatmap:
![adaptive_comfort_chart_rhino](https://user-images.githubusercontent.com/5567574/50375245-78375100-05c8-11e9-8fa1-b5fe1ebb8b49.png)

... as well as the psychrometric chart:
![psychrometric_chart_rhino](https://user-images.githubusercontent.com/5567574/50375250-884f3080-05c8-11e9-90d7-e2df7f096a19.png)

So I have been researching a couple of alternatives that can be used to refer specifically to the type of graphic that we currently call the "3D Chart."  Specifically I have noticed that OpenStudio team seems to be convinced that this type of graphic is called a "flood plot" as noted in the documentation of their results viewer:

http://nrel.github.io/OpenStudio-user-documentation/tutorials/running_your_simulation/#using-the-table-view-to-generate-a-flood-plot

https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-1.9.1-doc/resultsviewer/html/index.html

What I like about this is that OpenStudio team has only used this term to refer to the specific type of graphic that we are talking about here and so there does not seem to be any danger of having people mistake a flood plot for another type of visualization.  What makes me uncertain about adopting this name, however, is that I do not understand where this name comes from or what it has to with a "flood".  I'm thinking of asking OpenStudio team about this but, if anyone else knows anything about the etymology of this term, please share it here.  My confusion here might also just be grounds on its own for discounting it since new users aren't likely to recognize what the term means from its name.

Another possible option is to call it a "Temporal Plot", which has an etymology that is pretty straightforward and there is already a wikipedia article that specifically refers to the type of visualization we are taking about as a "Temporal Raster Plot":

https://en.wikipedia.org/wiki/Temporal_Raster_Plot

If it's clear from the two options that I'm considering here, I would like to use an existing term that is already used to refer to this specific type of graphic (rather than creating a new term).  If anyone has any other suggestions satisfying this criteria, please post them here!

**Comment by mostaphaRoudsari** [comment]
I vote for "Temporal plot"

**Comment by mostaphaRoudsari** [comment]
Should we transfer this to ladybug-grasshopper?

**Comment by chriswmackey** [comment]
I don't think that's appropriate.  The place where we have to decide the name first is on the module level of laydubug (ie. sunpath.py, windrose.py, and hourlyplot.py).

Also, I am a fan of "temporal plot" but I am starting to think that "hourly plot" might be a bit better just because there will probably be other charts like a monthly bar chart defined by their time interval.  I say this even though sub-hourly data can display on the "hourly chart".  We already established a convention of using "hourly" to refer to both hourly and sub-hourly data with the datacollection so maybe we should just continue the practice here.  I'll think on it some more and feel free to share any thoughts.

**Comment by chriswmackey** [comment]
As the name change here suggests, I'm really leaning towards "hourly plot" now.

**Comment by MingboPeng** [comment]
"Temporal Plot" +1

**Comment by saeranv** [comment]
I have no strong feelings about this, so am fine with anything, however my 2 cents: Hourly heatmap.

Because I think 'hourly heatmap' reflects that this is a specific instance (temporal/hourly) of an abstract type (heatmap). I like that the term 'heatmap' captures the fact that this plot represents three-dimensional data (in this case: hour of day, day of year, weather variable = 7 x 365 x 255). Map=2D spatial coordinates, Heat=color gradient.

Also heatmap seems to be the convention in the matplotlib world for these colored grid plots: https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/image_annotated_heatmap.html.

THEORY: Perhaps the reason NREL calls it a floodplot is because the color gradient reflects the contours of a landscape looking down along the z-axis. If you "flood" the plot, by clipping it along different ranges, you're effectively masking regions and identifying 'hotspots' in your data.

**Comment by chriswmackey** [comment]
Thanks for the input.

I wanted to say for the record that I understand that this visualization is a heatmap and I don't disagree that it is.  The issue that I have with using that term for the name of the module/class/component is that 90% of the graphics we produce with ladybug/honeybee are also heatmaps (all of the radiation/sunlight hours/daylight/view studies, the psych + adaptive charts, thermal comfort studies). So I'm not sure using "heatmap" in the title of the component or the module really helps us differentiate it from the other visualizations.  Conversely, there are (at most) 5 things in ladybug that might be considered a "plot" (hourly plot, monthly bar chart, line chart, psych chart, and adaptive chart). And, given that the word "chart" seems to describes the other 4 objects better than "plot", I think it's a really useful differentiator.

I'd agree that the word "heatmap" still has it's uses, though.  What if we changed the name of the "Recolor Mesh" component to "Spatial Heatmap".  I feel like most people never understood how useful that component is partly because it's name is overly-specific for all of the things it can do, which is essentially generate a heat map for any type of spatial study. So I think it benefits from the generality of the term in a way that the hour plot visual does not.

What do you think?

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/ladybug/pull/210
