### ISSUE TITLE
Get Rid of min_epw and max_epw Properties from DataTypes?

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#118]
I have been seriously considering getting rid of the `_max_epw `and `_min_epw `properties for a number of reasons:

- Though these min and max values are written into the EPW documentation, they do not seem to be enforced anywhere.  EnergyPlus still runs fine with many of these limits exceeded in its input EPWs.
- Nearly every EPW throughout the DoE and OneBuilding databases violates at least one of these min/max limits (the most common one probably being illuminance though I have also seen it with relative humidity, wind speed, atmospheric pressure, and others).
- I have been struggling to find situations where people would actually want to run a check to see if data is in min/max epw range given that many real data sets exceed them.

So I have been considering removing these properties or at least removing the ability to check if data is within the epw range just because it is misleading given that the limits written into the epw documentation seem to be arbitrary.

A related change that I feel more strongly about is that the missing_epw property should actually be stored in the [epw_fields object](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L1386-L1642) since it only really relates to the EPW and not a more general definition of data type.  I could also see us moving the min/max epw properties here if we realize they are useful and not arbitrarily chosen.

**Comment by mostaphaRoudsari** [comment]
I agree with removing them from datatypes but I think we should have them in epw_fields so in the future we validate epw files. True that no one cares at this point but that doesn't mean that we should let it go.

I can think of writing scripts (probably outside of the core library) that one can use for validating and fixing the epw files.

python epw-validate  <epw file>
&
python epw-fix <epw-file> <output-file>

which should print out a list of warnings and errors. We can at least report the issues with the current epw files to DoE and there is a good chance that we can convince a number of people to replace them with the fixed versions.

As a matter of face min, max and missing all used to be there in epw_fields: https://github.com/ladybug-tools/ladybug/blob/8057808b00c33093461379d695dd2932de584806/ladybug/epw.py#L836

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Ok, I will move everything to epw fields object for now and I should not have moved them out originally.

My point about the min and max values in the epw documentation, though, is that they are arbitrary and attempts to "fix" epw files will make them incorrect.  As the simplest example, nearly all climate files of Antarctica will be invalid if temperatures below -70C are not permitted.

I agree that we may generally want to have range checks in the future but I don't know if we really need to hold onto these arbitrary values so dearly.  I will leave them in for now but they really should be revised at some point.

**Comment by chriswmackey** [comment]
Ok. I have put together a PR that adds everything related to the EPW back to the EPW object and takes it out of the datatype module:
https://github.com/ladybug-tools/ladybug/pull/119

**Comment by mostaphaRoudsari** [comment]
> My point about the min and max values in the epw documentation, though, is that they are arbitrary and attempts to "fix" epw files will make them incorrect. As the simplest example, many climate files from Antarctica will be invalid if temperatures below -70C are not permitted.

I hear you. We can have a discussion about this with people in charge and try to change the epw specifications if needed.

**Comment by chriswmackey** [comment]
Understood.  I am closing out this issue now that we have merged in the PR.
