### ISSUE TITLE
Stat file contains no optical data.

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/ladybug#140]
Hi,
Some of the weather files for my location are failing on the TauClearSky component WEA). The error says:
`1. Solution exception:Stat file contains no optical data.`
Some other files are ok.
Something i can do?

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham (@ayezioro), while we are waiting for @chriswmackey's comprehensive response here is my 2 cents.

There is an alternative method (and a GH component) that uses ASHRAE's clear sky formula to generate the WEA file for locations that don't have the Tau values.

https://github.com/ladybug-tools/ladybug/blob/0caefbfa26195faba6bdedb242195f56eae1d770/ladybug/wea.py#L303

**Comment by chriswmackey** [comment]
@ayezioro ,

@mostaphaRoudsari 's is the correct way to go. There is a simpler clear sky model if there are no aerosol optical depths in the .stat file for a given location.  And there is already a component that uses the API method that @mostaphaRoudsari pointed to:
![image](https://user-images.githubusercontent.com/5567574/57091902-35088f80-6cd8-11e9-9d5d-340a7bda6dff.png)

https://drive.google.com/file/d/10bYld5iBo93zmllG3-VB_zqBwQTSkKbT/view?usp=sharing

You can also just use the Radiation data in the epw file but, for a case like solar-adjusted MRT in front of a reflective surface, you typically want a sunny summer day.

**Comment by ayezioro** [comment]
Thank you both!!
-A.
