### ISSUE TITLE
Ladybug error message even in the sample files

### ISSUE THREAD

**Issue by VanessaTavares** [ladybug-tools/ladybug#145]
Hi, 
I get the following error even when I run the ladybug in the sample file.

ERROR:
invalid literal for float (): DynamoForRevit

Traceback (most recent call last):
File "<string>", line 55, in <module>
File "<string>", line 18, in tryGetPluginPath
ValueError: invalid literal for float (): DynamoForRevit

![2](https://user-images.githubusercontent.com/51326350/59133643-acb88280-8946-11e9-953e-7433c247cd7d.JPG)
![1](https://user-images.githubusercontent.com/51326350/59133644-acb88280-8946-11e9-80be-b1362caa920a.JPG)

I am not into coding but need to run energy analysis on Dynamo!
Thank you very much!
Van

**Comment by chriswmackey** [comment]
@VanessaTavares ,

Energy modeling capabilities are not currently supported by Honeybee[+] (we are currently developing them now). Also, the most recent versions of Dynamo have broken the Honeybee[+] plugin for dynamo, which might be the error that you are expereincing here.  If you install a version of Dynamo from 2018, you might be able to get it to work but, if you need energy modeling capabilities, this still won't help too much.  I would recommend exporting room polygons from Revit to Rhino and using them to construct an energy model in Grasshopper.  That is how I built this ~100 zone energy model here:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Full_Building_Energy_Simulation&slide=1&scale=1&offset=0,0

Alternatively, I know that @theo-armour and @mdengusiak have made the [spider gbXML viewer](https://www.ladybug.tools/spider-gbxml-tools/#README.md) to help people clean up the (usually very messy) exports of gbXML files from Revit.

**Comment by VanessaTavares** [comment]
Hi Chris,
Thank you very much for your response. My problem is that I want to generate geometries in dynamo (already doing it) and after run them in different locations automatically so I could have results of various volumes, with different orientation, window-to-wall ratios and in different sites. When do you think Honeybee will be available? What do you think I should do? I feel kinda lost!
Thank you again for all your support!
