### ISSUE TITLE
TotalSunlightHours description problem

### ISSUE THREAD

**Issue by alexberd** [ladybug-tools/ladybug#152]
Dear Ladybug,

This is a documentation issue:
At the SunlightHoursAnalysis Tool, it is worth to mention that the totalSunlightHours result is per square meter. I spent few ours trying to investigate why this number is not the sum of the SunLightHoursResult. 
Could you please update the SunlightHoursAnalysis description at the following page and also at the Grasshopper? Description should be "The average number of hours of direct sunlight received by the test _geometry by square meter".
https://rhino.github.io/components/ladybug/sunlightHoursAnalysis.html
![image](https://user-images.githubusercontent.com/4086522/60764326-47f46300-a07f-11e9-81f1-3ea8a2bf5a28.png)

Below is grasshopper definition that explains how totalSunlightHours is calculated:
![image](https://user-images.githubusercontent.com/4086522/60764403-db7a6380-a080-11e9-984f-8aa1bae15987.png)

Many thanks

**Comment by mostaphaRoudsari** [comment]
@alexberd, Thank you for posting this issue but it should be posted to https://github.com/mostaphaRoudsari/ladybug/issues/

**Comment by chriswmackey** [comment]
Given that roughly a month has passed and the issue has hopefully been added to the legacy repo, I am going to close this one out.

**Comment by jandromani** [comment]
want to know the direct sunlight in a ground point for each day....

**Comment by mostaphaRoudsari** [comment]
@jandromani, this has been discussed on the forum: 
https://discourse.ladybug.tools/t/sunlight-hours-analysis-averaged-daily-sunlight-problem/4112

GitHub is for reporting bugs and development discussions.
