### ISSUE TITLE
Update several things in the formatting of the documentation

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#158]
Several changes need to be made to the documentation of this repo:
(check means we know how to fix them)

* Put any ASCII art in a .. code-block:: shell
* Put any dictionaries in from_dict methods in a .. code-block:: json
* Move all descriptions in `__init__` to be on the class itself.
* Get child classes to display documentation of their children
* Get the returns to display correctly (not bolded). Is do-able with @santiagogaray 's [solution here](https://github.com/ladybug-tools/ladybug-geometry/blob/master/docs/conf.py#L233-L285)
* Get properties and methods to be organized groupwise
* Get the navigation bar to not bleed onto the docs. Is doable with @santiagogaray 's solution [here](https://github.com/ladybug-tools/ladybug-geometry/blob/master/docs/_templates/layout.html), [here](https://github.com/ladybug-tools/ladybug-geometry/blob/master/docs/_static/custom.css)  and [here](https://github.com/ladybug-tools/ladybug-geometry/blob/master/docs/conf.py#L288-L298).
* Get all `Args` docstrings to use a standard on how to include the default values. Specifically, this should be `Default: False` at the end of the argument description (note that `False` should be replaces with the actual default value).

If anyone is up to the task, please go for it.  Otherwise, I can get to is after a few months.

**Comment by Kiy4h** [comment]
May I work on this? I'll be asking questions though.

**Comment by santiagogaray** [comment]
I actually have been working on it this week, I'm almost done with it.

**Comment by Kiy4h** [comment]
Oh whoops, sorry! I'll try to look for something else :)

**Comment by santiagogaray** [comment]
I'm sorry, my bad for not posting about it here!

**Comment by chriswmackey** [comment]
Sorry I could have been clearer about assigning this issue to @santiagogaray . @Kiy4h , if you want to see everything that we need help on, check our [hacktoberfest board](https://github.com/orgs/ladybug-tools/projects/2)

**Comment by chriswmackey** [comment]
Thanks again for addressing this one @santiagogaray .  This was a huge one!
