### ISSUE TITLE
Typo and grammatical mistakes in README file

### ISSUE THREAD

**Issue by parammittal16** [ladybug-tools/ladybug#168]
There are some grammatical issues in Readme file.
I want to correct them and work on this issue as of Hackoberfest.

**Comment by parammittal16** [comment]
@chriswmackey can we add hacktoberfest labels here?

**Comment by sakkshm** [comment]
can I do it?

**Comment by devgupta2607** [comment]
Can I take this issue ?

**Comment by AntoineDao** [comment]
Sorry @sakkshm and @devgupta2607 it seems @parammittal16 has already made a PR for this issue. If you're wanting to contribute and help us through hacktoberfest please check out our project board with all our [hacktoberfest issues](https://github.com/orgs/ladybug-tools/projects/2) and pick one from there. This hacktoberfest thing is not all about updating Readmes :stuck_out_tongue_winking_eye:

**Comment by chriswmackey** [comment]
This one has been addressed and so I am closing it out. Please take a look at the hacktoberfest board that @AntoineDao linked to for all of the stuff we need help with.
