### ISSUE TITLE
Ladybug 3D chart: adjust some details 

### ISSUE THREAD

**Issue by frank984** [ladybug-tools/ladybug#19]
Hello.

1) If the series of hourly data is not a multiple value of 24 hours, the horizontal lines of the graph curves are truncate to the previous full day. It could be better if the line completely fills the graph.

2) If I use the LBHeader and I define the unit, for example [°C], in the header I found something like this: ([°C]). If I exclude the square brackets and then in the unit I input only °C, in the upper limit of the legend I find °C and not (°C). So I think It would better to standardize the visualization of the u.m. in the graph with all the parenthesis (preferably square brackets).

![cattura](https://cloud.githubusercontent.com/assets/6491927/21926146/c9055fd0-d980-11e6-92a7-e8be7a4f7b59.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @frank984, Thanks for posting this issue and sorry that I didn't reply to this sooner. You should post this issue to https://github.com/mostaphaRoudsari/ladybug/issues as this is related to the legacy ladybug for Grasshopper.
