### ISSUE TITLE
Implement __slots__ on all objects

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#194]
While some of the classes in ladybug use `__slots__` right now, many do not and I imagine that this is because there has historically been a lot of refactoring. For the next release, we should implement `__slots__` on as many classes as we can.

**Comment by mkrueger12** [comment]
Does this issue still need help? I see some files have _slots_ now.

**Comment by chriswmackey** [comment]
I just wanted to add a note that we should NOT use `__slots__` on the Data Type classes as it will break ladybug_pandas and it doesn't save us much memory.

**Comment by chriswmackey** [comment]
Going through everything, I think this has been implemented in all of the cases where it matters. So I am going to close it out.
