### ISSUE TITLE
Add duplicate and __copy__ methods to all mutable objects

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#195]
The practice of using a publicly-available `duplicate` method that calls a private `__copy__` method is something that was critical for honeybee workflows and so nearly all mutable `honyebee-core` and `honeybee-energy` objects currently have this implemented. While these methods are a bit less critical for Ladybug, I think they will nevertheless be important for developers.  

Consider the following case:
Someone wants to make a Grasshopper component that changes an `AnalysisPeriod` to be for a `leap_year` (definitely not something we plan to support in the released components). Right now, if someone just writes a component that changes this property of the input analysis period, the `AnalysisPeriod` going into this component is going to get edited, thereby breaking our usual Grasshopper standard of passing in a certain object and getting out an edited object (leaving the original object unchanged). If, however, the `AnalysisPeriod` has a `duplicate` method on it, the user can just call this before going to make their edits and all is well.

So I propose we try to implement this on all mutable objects in Ladybug (maybe except for the EPW and STAT objects, for which there are less clear use cases).

**Comment by mostaphaRoudsari** [comment]
I agree that it can be helpful but specially for simpler objects why can't the user use `copy.deepcopy()` to make a new copy before modifying the object?
