### ISSUE TITLE
Refactor the sunpath module to use ladybug_geometry instead of sunpathplus

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#208]
This is the last thing that needs to be done to rid the ladybug plugin of its dependency on the extra sunpathplus and geometry modules that uses Rhino SDK.

**Comment by mahaidong** [comment]
hi @chriswmackey 
what is  sunpthpluse mean? 
how can i do this `import sunpathplus as plus`  , where is sunpathplus from?

**Comment by mostaphaRoudsari** [comment]
@mahaidong, you should open a new issue for this. Also you won't need sunpathplus if you are not running it from inside Grasshopper. If you have a follow up question either open a new issue or post a topic on the forum. Thanks.

**Comment by chriswmackey** [comment]
This was addressed via https://github.com/ladybug-tools/ladybug/pull/214
