### ISSUE TITLE
Add module for WindRose

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/ladybug#211]
Add a windrose module to ladybug. 

References for this include:
- the hourlyplot PR (in terms of general code style/structure for the + classes): https://github.com/ladybug-tools/ladybug/pull/210.
- the legacy component (for windrose properties): https://github.com/ladybug-tools/ladybug-legacy/blob/master/src/Ladybug_Wind%20Rose.py

@chriswmackey anything to add?

**Comment by mostaphaRoudsari** [comment]
Isn't this already addressed? Should we close this issue?

**Comment by saeranv** [comment]
Yes, this is done. Thanks for reminding me to close this.
