### ISSUE TITLE
Total Radiation,Windrose are not the same size with same settings

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/ladybug#22]
Hi,

I am setting up some template and total radiation
I set up scale  and apply legend to get same min and max
I am trying to get unified text size in legend but with wind rose using 0.17 and with radiation 0.7,
Maybe could be scope to get one scale factor across all components.
Idea is when we type one scale we achieve same standard test across all components. 
Any idea why I can not unified sizes?

![image](https://cloud.githubusercontent.com/assets/14005893/25594880/73a61bf8-2eba-11e7-9ad1-519c91053d10.png)

I have same with Windrose

![image](https://cloud.githubusercontent.com/assets/14005893/25594969/e48e8bc0-2eba-11e7-9e1d-62b3bc53e5ec.png)

**Comment by mdengusiak** [comment]
I am using separate component so each graph just show one set of data and is not connect to other data. So in fact it is correct. I can use scale but there each time I have to adjust each graph. 
Maybe could be interesting idea that we can connect few components together and somehow re-use scale or size value... to fix sizes?

**Comment by mostaphaRoudsari** [comment]
Hi @mdengusiak, this issue should be posted under the [legacy version repository](https://github.com/mostaphaRoudsari/ladybug). Also if I'm not mistaken this is already resolved for wind rose using maximum frequency input.

![image](https://user-images.githubusercontent.com/2915573/28602225-cefa540c-718a-11e7-86df-f30b4c3d9ef6.png)
