### ISSUE TITLE
"No module named OS" ERROR producing null outputs

### ISSUE THREAD

**Issue by SebasOrozco** [ladybug-tools/ladybug#25]
Hi everybody. Thank you _chriswmackey_ for redirecting me here.
My original question/issue is as follows:

I´m just starting to try out Ladybug on Dynamo, for preliminary environmental analysis, but came across what must be a really simple/naive mistake... I hope
For some reason I´m getting null outputs from every node when running the basic sample files.
I´ve tried several DYN/LB versions and combinations with the exact same results... All I´ve been able to track down so far is this error message by using watch nodes attached to the ERRReport outputs.
![image](https://user-images.githubusercontent.com/29990157/28122991-0ee056ce-66dd-11e7-9fa8-79af17b179c9.png)
This happens regardless I use my own .EPW´s, or the ones available from your download map (DOE). I even tried rebuilding the whole definition from scratch based on your tutorial videos, but still no luck...

I´m using Win7 with RVT 2016, just in case you need to know...

Sorry to bother you with such a basic issue, hope to hear from you soon!
Regards from Costa Rica.

**Comment by mostaphaRoudsari** [comment]
Hi @SebasOrozco, Do you have IronPython installed on your machine? Can you tell me where is it installed if it is?

Also not to confuse you more but this issue which is related to ladybug-dynamo should be posted [here](https://github.com/ladybug-tools/ladybug-dynamo).

**Comment by SebasOrozco** [comment]
Hi @mostaphaRoudsari, thanks for your reply!
Apparently I had IronPython 2.7.3 runing already when the first null results came up... I´ve updated to 2.7.7 now, but still no luck... The Analysis Period node, keeps giving me null "analysisPeriod" output.
![capture](https://user-images.githubusercontent.com/29990157/28277489-5ac929c8-6ad7-11e7-9fee-a48187602be2.PNG)
I´m using Dynamo 1.3.0.875, along with LadyBug 0.1.7
Got no idea what´s missing, so I´ll try to start all over again in a couple of different machines to try and spot the bug.
If you think of something else, I´d greatly appreciate your guide.
Thanks Again.
Sebas

Ps. I´ll switch to the other forum from here on.

**Comment by mostaphaRoudsari** [comment]
Hi @SebasOrozco,

A good way to debug this issue is to take the python component from inside the custom node and try to run it inside the dynamo. That way we can see the errors.

The error can be because of any of this:
1. Python node cannot find the python installation on your machine.
2. Python node cannot find ladybug package.

We can continue this discussion on the forum. Thanks.
