### ISSUE TITLE
add legend units to legend parameters

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug#28]
and maybe the analysis name

**Comment by devngc** [comment]
On wind rose, I will have an input for legendPar_. At that point, I believe, I will have to address this. Therefore, assigned to myself.

**Comment by chriswmackey** [comment]
I aim imagining that this will now mostly be taken care of thanks to the datatype module objects that store all of the units.  Let me know if you are thinking about this differently, @mostaphaRoudsari (like if you think people would want to change the display of the units even though the units in the background are unchanged).  Needless to say, I think we all probably feel there are a bunch of improvements that can be made to legend parameters.

**Comment by mostaphaRoudsari** [comment]
Mostly yes but it is a slightly different issue. `datatype` will be helpful to make the value conversion easier and so on but this issue is trying to _where_ is the right place to input that change rather than _how_ to make the change.

Based on what I wrote at the time I thought it should be part of the legend parameters class but now we can think of other solutions to address this using DataCollection class and its functionalities.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I think you can close this one after you merge the latest changes.

**Comment by chriswmackey** [comment]
Good idea. Closed!
