### ISSUE TITLE
Epw header omits out location data

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/ladybug#29]
Hi @mostaphaRoudsari , due to the use of generator patterns the first line of the existing epw file does not get written into the new (saved) epw file. The culprit is here : https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L68-L94 . When you do the first `epw.readline()` on [line 69](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L68-L94), that first line will not be available when you do ` self.epwHeader = [epwin.readline() for i in xrange(7)]` on [line 94](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L94). 

So, if the original file is ....

> LOCATION,New York City/Central,NY,USA,TMY--94728,.94728,40.78,-73.96,-5.0,40.0
> DESIGN CONDITIONS,0
> TYPICAL/EXTREME PERIODS,6,Summer - Week Nearest Max Temperature For Period,Extreme,8/24,8/30,Summer - Week Nearest Average Temperature For Period,Typical,6/29,7/ 5,Winter - Week Nearest Min Temperature For Period,Extreme,12/22,1/ 5,Winter - Week Nearest 

....the saved file that I found was ...
> DESIGN CONDITIONS,0
> TYPICAL/EXTREME PERIODS,6,Summer - Week Nearest Max Temperature For Period,Extreme,8/24,8/30,Summer - Week Nearest Average Temperature For Period,Typical,6/29,7/ 5,Winter - Week Nearest Min Temperature For Period,Extreme,12/22,1/ 5,Winter - Week Nearest 

I am pretty sure it's because the first line was read [here](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L69-L88). Not a very elegant fix but changing `self.epwHeader = [epwin.readline() for i in xrange(7)]` to `self.epwHeader = [line] [epwin.readline() for i in xrange(7)]` on [line 94](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/epw.py#L94) will fix the issue.

**Comment by mostaphaRoudsari** [comment]
@sariths this is a bug. thanks.

Now that I see this again I should have read all the header first and then get the location out of it. That would have avoid this issue.

**Comment by mostaphaRoudsari** [comment]
Fixed by @sariths
