### ISSUE TITLE
Refine Sunpath code

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug#31]
[Ladybug legacy Sunpath](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_SunPath.py) gives slightly different results than [NOAA solar calculator](https://www.esrl.noaa.gov/gmd/grad/solcalc/).

I made a number of adjustments in order to fix the difference in Ladybug[+] but I ended up making it worse. The source code is available [here](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/sunpath.py)

We need to check this once and forever and write a number of test to make sure no upcoming change will affect the accuracy of the code.

@devngc will be in charge.

PS: This is one of the first classes that I wrote for Ladybug[+] and should have a lot of room for improvements.

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari @devngc any luck with this?

**Comment by devngc** [comment]
@ParametricMonkey ,
Apologies for the delay. I just saw this. I will update here as soon as I fix this.

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari This issue has been closed but has it been implemented into Dynamo yet? I'm on the latest version 0.1.9.

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari how did you go with the internal deadline?

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey! Sorry for the delay. I'm writing the release notes right now! Expect it out in a day or two.
![image](https://user-images.githubusercontent.com/2915573/35940589-ac44e0de-0c1d-11e8-807e-ff53d28814bf.png)

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari @devngc 
I've been revisiting this and there still seems to be a discrepancy. Using Ladybug 0.2.1 in Dynamo with Revit 2018, I'v created views from the sun and then turned on shadows. There should be no shadows visible but it is slightly out.  Does this mean that Revit doesn't use NOAA or is there a bug in Ladybug?

![image](https://user-images.githubusercontent.com/10913639/65206815-1feb9c00-dad3-11e9-9237-cc8a20061c32.png)

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey does the location exactly match? Can you get the sun vectors from Revit? That is the only way to do a legit comparison between the two and NOAA algorithm. Also this might deserve a new issue or a question on the forum.

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari 

posted here: https://discourse.ladybug.tools/t/solar-vector-discrepancy/7220
