### ISSUE TITLE
Weather data headers

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/ladybug#39]
Hi @mostaphaRoudsari,

In Ladybug[+], the LadybuPlus_Import EPW component outputs hourly values of weather data and the header is missing. In legacy plugins, this header is used to identify annualHourlyData_ in components like sun path or wind rose. I am sure you have some different idea about doing this in the core library. Can you please share your thoughts on this?

The way I see it, we need to have a separate component to add a header to the data. Please correct me if I am wrong here.

Thank you!
Devang

**Comment by mostaphaRoudsari** [comment]
Hi @devngc,

To answer this question we should first separate the discussion for the core python library and the Grasshopper plugin. Grasshopper plugin has its own challenges that we can address later in its own context.

In Ladybug EPW class returns a [DataCollection](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datacollection.py#L10) for each data type and DataCollection has a [header](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datacollection.py#L63) property which will return an object of type of [Header](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/header.py#L9). In other words it's already implemented but it's not exposed in Grasshopper interface.

If you want to see the header try this:

```python
from ladybug.epw import EPW
epw_data = EPW("./tests/epw/chicago.epw")
annual_db = epw_data.dry_bulb_temperature
print(annual_db.header)

> Chicago Ohare Intl Ap, lat:41.98, lon:-87.92, tz:-6.0, elev:201.00|Dry Bulb Temperature(C)|1/1 to 12/31 between 0 to 23 @1
```
Now what is the difference between the data collection and the list? and why we won't probably need a header for the list in Grasshopper interface? 

The difference is that in DataCollection each item is a `DataPoint` which has a `value` and a `datetime`. For instance if for the example above if you print the items the output will be:

```Python
-12.2 at 01 Jan 00:00
-11.7 at 01 Jan 01:00
-11.1 at 01 Jan 02:00
-11.1 at 01 Jan 03:00
-10.6 at 01 Jan 04:00
-10.6 at 01 Jan 05:00
-10.6 at 01 Jan 06:00
-10.0 at 01 Jan 07:00
-8.9 at 01 Jan 08:00
-6.7 at 01 Jan 09:00
...
```

This will solve half of the problem with the header as we know the datetime for each data point and we know each type of data it is if we check the type. I have not finished implementing all the datatypes and for now every data is a [Generic DataPoint](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datatype.py#L233). But once the datatype is implemented you will have [Temperature](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datatype.py#L274), [RelativeHumidity](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datatype.py#L337), etc which will be passed between the components.

**Comment by devngc** [comment]
Thank you @mostaphaRoudsari for demonstrating this. I realized this when I tried to use the output of Ladybug_ImportEPW component. Instead of values, it contains [DataPoint](https://github.com/ladybug-tools/ladybug/blob/cc40c6d601b3f74f6283913f2517448bf4ddc676/ladybug/datatype.py#L233) objects.
