### ISSUE TITLE
Bug: epw.py if call epw.import_data() twice the import looks all wrong

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/ladybug#50]
This is a minor bug I noticed while writing tests for ladybug: if I call import_data twice on the EPW object then the imported data looks all wrong. I realise this is a total edge case so don't expect it to be fixed urgently but maybe worth having a look at a fix?
![image](https://user-images.githubusercontent.com/20436635/42003370-095d9f82-7a63-11e8-8c6d-bbf77d72c4f8.png)
![image](https://user-images.githubusercontent.com/20436635/42003421-3dae1b22-7a63-11e8-9147-aee726894cd9.png)

**Comment by mostaphaRoudsari** [comment]
@AntoineDao thank you for reporting this.
