### ISSUE TITLE
Add a WindProfile Class

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#562]
This should work similar to how the SunPath works where people can use it simply to get the wind speed at a given height or they can optionally get a fully-detailed visualizations.

**Comment by krishnaduttPanchagnula** [comment]
Hi @chriswmackey can we do this with visual crossing api key( It has limit of about 10,000 requests) per day? I tested out a piece of code. Would be happy to share if you are fine with it.

**Comment by chriswmackey** [comment]
This has now been implemented so I am closing the issue.

I'm don't think I understand your question, @krishnaduttPanchagnula , but it seems separate from the original issue and I'd recommend opening a different issue if you want to discuss it further.
