### ISSUE TITLE
Introduction of numpy and vectorization  of the inbuilt definitions for performance improvement

### ISSUE THREAD

**Issue by IHoldYA** [ladybug-tools/ladybug#579]
Hi, I was recently testing the ladybug tools package within external python environment and was wondering whether there are any plans for the code optimization by using numpy data arrays instead of native python lists and dictionaries as well as definitions' vectorization? 
I am asking as this could increase the computation time significantly. I was even considering partly rewriting it myself for the sake of my projects.

cheers!

**Comment by mostaphaRoudsari** [comment]
Hi, @IHoldYA - we use the ladybug core libraries from inside Rhino/Grasshopper and we need to keep them compatible with IronPython. As a result we can't add dependencies like numpy to the core library.

That said, you can create your own extension that does what you want. See `ladybug-pandas` as an example:  https://github.com/ladybug-tools/ladybug-pandas/

**Comment by chriswmackey** [comment]
I think the ladybug-pandas repo essentially answers this question so I'm closing it. If there are further questions in this regard, they should probably be asked on the ladybug-pandas repo.
