### ISSUE TITLE
There is no euclid support for Python 3.

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/ladybug#59]
@mostaphaRoudsari , @chriswmackey 

The library crashes if you try to import sunpath in Python 3, as there is currently [no "euclid3" in the repo](https://github.com/ladybug-tools/ladybug/blob/master/ladybug/sunpath.py#L8-L11).

I fixed the issue in my fork by adding and renaming the file: https://github.com/sariths/ladybug/commit/c60f28cab5dd8b132e5c5533d9e5a696f868811e

I can send a PR if needed.

**Comment by mostaphaRoudsari** [comment]
Try `pip install euclid3` for Python 3 and you will have it.

**Comment by saeranv** [comment]
And I think we should be updating the setup.py file to reflect these dependencies: https://github.com/ladybug-tools/ladybug/blob/master/setup.py

For Python 2, it should be as simple as adding euclid:
install_requires=[
          'euclid',
      ],

And there must be a way to differentiate dependencies based on Python versions.
