### ISSUE TITLE
Click v7 Dependency Incompatibility

### ISSUE THREAD

**Issue by ed-p-may** [ladybug-tools/ladybug#597]
Hi, 

I am running into trouble with the 'Click v7' dependency requirement. Currently this dependency appears to be [pinned as v7.1.2](https://github.com/ladybug-tools/ladybug/blob/25f88a22b1ca9adfa2ad6ee77711746ff6b12361/requirements.txt#L2), however Click appears to now be up to [v8.1.3](https://pypi.org/project/click/)

The reason that I notice is that when ladybug-core is installed alongside some other packages, a version incompatibility warning will get thrown by pip. Notably: the current version (23.3.0) of the autoformatter "Black" requires [click >8](https://github.com/psf/black/blob/f265ff5bcd0eafcde1e62df89fb8b62ad1439887/pyproject.toml#L66). This incompatibility means that any package using ladybug-core breaks Black, and autoformatting no longer works.

The workaround seems to be to install the older version of [Black (v23.1.0)](https://pypi.org/project/black/23.1.0/) for now.

Is it possible to update this click dependency to the current version?

thank you!
Ed, @PH-Tools

**Comment by chriswmackey** [comment]
I forgot to close out this issue as we addressed it a long time ago:

https://github.com/ladybug-tools/ladybug/commit/0f491dea92cdd697daccc6690e21fa7aab253eeb
