### ISSUE TITLE
EPW design conditions

### ISSUE THREAD

**Issue by cmsavage** [ladybug-tools/ladybug#604]
It looks like some recent TMY EPW files on OneBuilding.org have a different format for the design conditions line ("2021 ASHRAE Handbook -- Fundamentals - Chapter 14 Climatic Design Information") that is different from what the EPW module is expecting form import (2009 ASHRAE?).  The number of heating/cooling/extreme fields do not match, but I do not have a copy of the 2021 ASHRAE Handbook of Fundamentals to check what the new format might be.  Relevant areas that would require updating (would need to newly keep track of the "design condition source" field instead of assuming 2009 ASHRAE?):

https://github.com/ladybug-tools/ladybug/blob/e70767b655e0c62da2efdf73cbb966d6ae3929d6/ladybug/designday.py#L69-L83
https://github.com/ladybug-tools/ladybug/blob/e70767b655e0c62da2efdf73cbb966d6ae3929d6/ladybug/epw.py#L445-L455
https://github.com/ladybug-tools/ladybug/blob/e70767b655e0c62da2efdf73cbb966d6ae3929d6/ladybug/epw.py#L809-L817

**Comment by mostaphaRoudsari** [comment]
Hi @cmsavage, Thank you for letting us know. I assigned @chriswmackey to this issue so he is aware of this issue.

**Comment by chriswmackey** [comment]
Sorry it took me sol long to address this, @cmsavage . Thanks for bringing it to my attention. I am merging a fix now that can handle the new ASHRAE 2021 design day format. FYI, this website was helpful for me seeing the difference between the 2009 and 2021 fields:

https://ashrae-meteo.info/

As expected, there wasn't really that much that changed. They added a new field for heating design days called "Weather and shielding factor". And they shuffled a key around between the cooling design day and the extreme conditions. Just to make it difficult for all of us software developers 🙃 .
