### ISSUE TITLE
How do I install Ironbug on my macbook（macOS）？

### ISSUE THREAD

**Issue by buger-killer** [ladybug-tools/ladybug#617]
Does anyone use this plugin on Mac? 
There is no pollination one-click installation for Mac, and there is no corresponding Ironbug installation package on github.

**Comment by mostaphaRoudsari** [comment]
You should post this question on Discourse. 

I don't know about the Ironbug but the single click installer is Windows only.

**Comment by chriswmackey** [comment]
I agree with Mostapha. Or you can post this to the [IronBug GitHub](https://github.com/MingboPeng/Ironbug). Maybe @MingboPeng has an idea for how to hack it.
