### ISSUE TITLE
Error with conversion between area-normalised/area-aggregated units

### ISSUE THREAD

**Issue by tg359** [ladybug-tools/ladybug#627]
I've found a bug with the `aggregate_by_area `and `normalize_by_area `methods for some of the conversions. It seems to be that where units contain a "/" character in the unit string stop the conversion from working. I've found this on the following conversions:
- `VolumeFlowRate `> `VolumeFlowRateIntensity`
- `VolumeFlowRateIntensity `> `VolumeFlowRate `
- `Power`> `EnergyFlux`
- `EnergyFlux`> `Power`
(so pretty much anywhere that the unit is {unit}/{unit}-{area-unit})

Below is an example:
![image](https://github.com/user-attachments/assets/6fc800ea-816b-4f56-ac22-fe7b49c76635)

**Comment by chriswmackey** [comment]
Thanks for pointing this out, @tg359 . And for posting the issue to the right repo (I know that we have a lot of them). I'll see if I can fix this later today.
