### ISSUE TITLE
Ladybug doesn't work on dynamo 2.0 ??

### ISSUE THREAD

**Issue by PNTheBao** [ladybug-tools/ladybug#64]
Hello! Ladybug doesn't work on dynamo 2.0! what is the problem? I've checked the installed folder as follow the solution at previous topic : C:\Users\UserName\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages
Please advise. Thank you.
![ladybug 01](https://user-images.githubusercontent.com/41409560/42919903-ba3bdd48-8b46-11e8-8736-a6c73b81f5c1.PNG)
![ladybug 02](https://user-images.githubusercontent.com/41409560/42919989-2bedef76-8b47-11e8-8bcd-97359e17ccc2.PNG)
![ladybug 03](https://user-images.githubusercontent.com/41409560/42919995-327cc5ce-8b47-11e8-97ec-8eebe054dd0f.PNG)

**Comment by chriswmackey** [comment]
@PNTheBao and @JoshuaC-STN ,
I'll try to take a look at this today.

To narrow down the possible issues, can you confirm that this issue affects all components in both Ladybug and Honeybee?

**Comment by PNTheBao** [comment]
@chriswmackey Yes, same issue to Butterfly and Honeybee.
![issue 2](https://user-images.githubusercontent.com/41409560/43355346-39d9f808-928d-11e8-8119-a87849c4fd2f.JPG)

**Comment by mostaphaRoudsari** [comment]
This is because the path structure for packages has slightly changed in Dynamo 2. This is a low-hanging fruit but installing Dynamo 2.0 is what has stopped me from addressing this issue.

**Comment by PNTheBao** [comment]
So how we solve this issue, waiting the next version ?

**Comment by mostaphaRoudsari** [comment]
I just released a new version for all ladybug tools plugins for Dynamo which should address this issue.
