### ISSUE TITLE
Iron-Python-check and stricter versioning for dependencies

### ISSUE THREAD

**Issue by sariths** [ladybug-tools/ladybug#80]
Hi @mostaphaRoudsari , @chriswmackey  and @AntoineDao , 

Since dependencies are now being added through setup.py,  a few suggestions:
* Since IronPython 2.x is an incomplete port of Python 2.x, it might save some headaches later if there is some of testing to see if the dependency is not using some of the fancier features of Python 2 (xml is one of the modules that comes to mind).

* I highly recommend adding the version number to dependencies in `install_require`. For example, over [here](https://github.com/ladybug-tools/ladybug/blob/master/setup.py#L31-L33), it is safer if `euclid3` is `euclid3==0.01`. This isn't a big issue for euclid3 per se, but will likely be for more complex pacakges (I learnt this the hard way!).

**Comment by AntoineDao** [comment]
From my understanding we should be able to add IronPython as a tested environment in Travis. So we would test IronPython, Python 2.7 and Python 3.6.

Also with regards to dependency versioning I absolutely agree! Is `euclid3==0.0.1` the correct version to use? If so I'll PR IronPython test support + euclid version check.

**Comment by sariths** [comment]
> Also with regards to dependency versioning I absolutely agree! Is euclid3==0.0.1 the correct version to use?

0.1 should be the version that is installed through `pip`. I just checked using `pip freeze`
![image](https://user-images.githubusercontent.com/10361848/48065067-f29f4380-e1c9-11e8-9f80-8b4ac368c759.png)
I couldn't find the source code on the pypi webpage for euclid3

**Comment by mostaphaRoudsari** [comment]
![image](https://user-images.githubusercontent.com/2915573/48109294-f5b63480-e29a-11e8-8a54-c42b2e37f437.png)

**Comment by sariths** [comment]
@sariths I know.  But just doing `pip install euclid3` installs euclid3==0.1 on my system (as the `pip freeze `screenshot shows). I think there is a versioning mismatch somewhere. There is a repo on github for euclid3, however, that doesn't appear to be really active at the moment.

**Comment by AntoineDao** [comment]
Should we just add euclid manually to ladybug? Or wait for [ladybug-geometry](https://github.com/ladybug-tools/ladybug-geometry) to become a thing?

**Comment by AntoineDao** [comment]
If discussion version control etc.. then a mix of `requirements.txt` with versioned packages (eg: euclid3==0.1) and deploying ladybug-tools with [version management](https://discourse.ladybug.tools/t/semantic-releases/4159) should do the trick. I'm not worried about euclid3 as the last release was in 2014 and the package is minuscule but it's a good habit to get into!

As for IronPython @mostaphaRoudsari I had a major scan and you're right we can't test it on Travis... @sariths would you mind listing the modules available in Python 2.x but not IronPython so we can sticky them somewhere and let folk know not to use them when building for grasshopper/dynamo?

**Comment by sariths** [comment]
> @sariths would you mind listing the modules available in Python 2.x but not IronPython so we can sticky them somewhere a

For me it is usually trial and error. A year ago, we had this idea of implementing a BSDF viewer inside Rhino and that time I found xml wasnt completely ported. That apparently is the case for some other libraries.. https://stackoverflow.com/a/6855252 . I am not sure if there is a definitive list somewhere.

**Comment by mostaphaRoudsari** [comment]
What about running the tests for IronPython locally?

We set up a half-backed Grasshopper based testing for components at some point which can also be used for this purpose.

I see that @AntoineDao has send a PR to get the versioning fixed. The main reason that I didn't put the version was the fact that:

1. `euclid3` is not an actively developed project and won't be updated any time soon.
2. it will be replaced by `ladybug-geometry`.

In any case putting the version is good practice so let's do that!

**Comment by AntoineDao** [comment]
I reckon there is a strong enough community of people using ladybug tools on Windows to ensure testing IronPython locally and in the right environment. But you'll have to excuse me if I don't notice incompatibilities from the luxury of my Linux machine :p

**Comment by mostaphaRoudsari** [comment]
> But you'll have to excuse me if I don't notice incompatibilities from the luxury of my Linux machine :p

You lucky [...]! :)

**Comment by chriswmackey** [comment]
I just wanted to say that we are only using euclid right now for vector math and putting the vector math in ladybug-geometry is pretty straightforward. It's just a matter of taking the parts of euclid that are needed for vector math and making them compatible in both Python 2 and Python 3.  So I think we should be able to get rid of this euclid dependency fairly soon.
