### ISSUE TITLE
Refactor the DataCollection Class into Several Sub-Classes

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug#82]
Data collection structure proposal:
![planfordatacollections](https://user-images.githubusercontent.com/5567574/48262254-dc72cc80-e3ef-11e8-8423-45901740f4ac.jpg)

**Comment by chriswmackey** [comment]
While I am doing this, I also should separate out the type objects so that each datacollection has only one type object.  In other words, datacollections will only contain data that is all the same type.

This will greatly reduce that size and memory taken up by datacollection objects.

**Comment by AntoineDao** [comment]
Got two questions for you about this:

1. Not sure I fully understand the difference between hourly collections and cumulative collections. ie: what is the difference between `monthly annual` and `monthly`?

2. Will the data collection data-points still hold a lot of individual data (specific type, name, metric unit, datetime etc...) or will the role of collection be to hold this sort of metadata?

**Comment by chriswmackey** [comment]
No worries, @AntoineDao .  We're basically using github like a chatting app :)

I will say that there are a lot of things that are not totally worked out yet (especially the naming conventions).  I am just posting how far @mostaphaRoudsari and I have gotten in discussing this so that we have record.

To explain the difference between `monthly hourly` and `monthly`, `monthly hourly` is a data collection that has values for each hour over an entire month.  `monthly` is a data collection that has 12 values with each value representing the total or average of each month.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, I think we can also close this one. It would be good if you can take a look at the open issues and close the ones that are already addressed with your PR.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/ladybug/pull/110

And the final inheritance tree that I drew at the top of this issue looks much better in its final form as ASCII art:
https://github.com/ladybug-tools/ladybug/blob/master/ladybug/datacollection.py#L4-L14

**Comment by AntoineDao** [comment]
---------------------
< Beautiful Ascii Art >
 ---------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
